- name: "check if OS is compatible"
  fail:
    msg: "Failed: the OS which you tried is incompatible"
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_architecture == "x86_64") and
        not (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7" and ansible_architecture == "x86_64")

- name: "set facts"
  set_fact:
    gathered_distribution: "{% if ansible_distribution == 'RedHat' %}rhel{% elif ansible_distribution == 'CentOS' %}centos{% endif %}"
    gathered_arch: "{% if ansible_architecture == 'x86_64' %}amd64{% endif %}"

- name: "install yum-utils"
  package:
    name: "yum-utils"
    state: latest