- name: copy mariadb.repo
  template:
    src: mariadb.repo.j2
    dest: "{{ mariadb['repo_file'] }}"

- name: install mariadb packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - mariadb-server
    - mariadb

- name: enable and start mariadb service
  systemd:
    state: restarted
    enabled: yes
    name: mariadb