- name: "[configure] unset {{ php['conf_file'] }} listen port"
  lineinfile:
    dest: "{{ php['conf_file'] }}"
    backrefs: yes
    state: present
    regexp: "^(;|)(listen = 127.0.0.1:9000)$"
    line: ";\\2"

- name: "[configure] set {{ php['conf_file'] }} listen socket"
  lineinfile:
    dest: "{{ php['conf_file'] }}"
    backrefs: yes
    state: present
    regexp: "^(;|)(listen = /run/php-fpm/www.sock)$"
    line: "\\2"

- name: "[configure] set {{ php['conf_file'] }} listen.acl_users"
  lineinfile:
    dest: "{{ php['conf_file'] }}"
    backrefs: yes
    state: present
    regexp: "^(;|)(listen.acl_users = nginx)$"
    line: "\\2"

- name: "[configure] set {{ php['ini_file'] }} cgi.fix_pathinfo"
  lineinfile:
    dest: "{{ php['ini_file'] }}"
    backrefs: yes
    state: present
    regexp: "^(;|)(cgi.fix_pathinfo)(=.*)$"
    line: "\\2=0"

- name: "[configure] copy php.conf"
  template:
    src: php.conf.j2
    dest: "{{ php['nginx_conf']['php_file'] }}"

- name: "[configure] copy php-fpm.conf"
  template:
    src: php-fpm.conf.j2
    dest: "{{ php['nginx_conf']['php-fpm_file'] }}"

- name: "[configure] enable and start php-fpm service"
  systemd:
    state: restarted
    enabled: yes
    name: php-fpm