- name: unset {{ php['conf_file'] }} listen port
  lineinfile:
    dest: "{{ php['conf_file'] }}"
    backrefs: yes
    state: present
    regexp: "^(;|)(listen = 127.0.0.1:9000)$"
    line: ";\\2"

- name: set {{ php['conf_file'] }} listen socket
  lineinfile:
    dest: "{{ php['conf_file'] }}"
    backrefs: yes
    state: present
    regexp: "^(;|)(listen = /run/php-fpm/www.sock)$"
    line: "\\2"

- name: set {{ php['conf_file'] }} listen.acl_users
  lineinfile:
    dest: "{{ php['conf_file'] }}"
    backrefs: yes
    state: present
    regexp: "^(;|)(listen.acl_users = nginx)$"
    line: "\\2"

- name: enable and start php-fpm service
  systemd:
    state: restarted
    enabled: yes
    name: php-fpm