- name: install epel repository for centos
  package:
    name: "epel-release"
    state: latest
  when: ansible_distribution == 'CentOS'

- name: install epel repository for rhel
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_distribution == 'RedHat'

- name: install epel rpm key
  command: 'rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'

- name: install ius repository
  package:
    name: "https://{{ gathered_distribution }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
    state: present

- name: install epel rpm key
  command: 'rpm --import /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY'

- name: install php packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php['packages'] }}"