- name: install epel repository for centos
  package:
    name: "epel-release"
    state: latest
  when: ansible_distribution == 'CentOS'

- name: install epel repository for rhel
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_distribution == 'RedHat'

- name: enable {{ php['enable_repo'] }} repository
  command: "yum-config-manager --enable {{ php['enable_repo'] }}"

- name: install REMI repository
  package:
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: install php packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php['packages'] }}"